import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'

const fontSans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create your business',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={`${fontSans.className} mx-auto w-3/4`}>{children}</body>
        </html>
    )
}
